# SSH model
Hamiltonian :
$$H_{SSH}=\sum__{x=1}^{L}-t(1-(-1)^x\delta)(c_x^\dag c_{x+1}+g.c.).$$


In [150]:
import numpy as np
from matplotlib import pyplot as plt
plt.switch_backend('agg')
import scipy as sp

In [164]:

def construct_ham(L=10,delta=0.2,t=1):
    mask = np.ones(L-1, dtype=bool)
    mask[::2] = 0
    
    tridig1=np.arange(L-1)
    tridig1[mask]=0
    tridig2=np.arange(L-1)
    tridig2[~mask]=0
    H=np.empty([10,10])
    H[tridig1,tridig1+1]=-t*(1-delta)
    H[tridig2,tridig2+1]=-t*(1+delta)
    H[tridig1+1,tridig1]=-t*(1-delta)
    H[tridig2+1,tridig2]=-t*(1+delta)
    ##fix:
    H[0,1]=t*(1-delta)
    H[1,0]=t*(1-delta)
    return H



In [173]:
L=10
fig1=plt.figure()


p=np.linspace(0,2,400)
for x in p:
    delta=x
    test=construct_ham(L,x)
    xvalue=np.empty(L)
    xvalue.fill(x)
    
    E,v = np.linalg.eig(test) ##diagonalisieren
    
    plt.plot(xvalue,E,'b.',markersize=0.8) ##plotten

plt.xlabel('delta')
plt.ylabel('energy')
plt.savefig('plot.pdf')


print(test)





[[ 0. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  0. -3.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -3.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0. -3.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -3.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0. -3.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -3.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0. -3.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -3.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]]
